name: Node.js CI

# Define when the workflow should run
on:
  push:
    branches: [ main ] # Run on every push to the main branch
  pull_request:
    branches: [ main ] # Run on every pull request to the main branch

jobs:
  build: # Name of the job

    runs-on: ubuntu-latest # The job will run on the latest version of Ubuntu

    strategy:
      matrix:
        node-version: [16] # Specify the version of Node.js to use

    steps:
    - uses: actions/checkout@v2 # Step to check out the repository code

    - name: Use Node.js ${{ matrix.node-version }} # Step to set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }} # Use the specified Node.js version
        cache: 'npm' # Cache npm dependencies for faster builds

    - run: npm ci # Install dependencies using npm ci
    - run: npm test # Run the tests

    - name: Build and Push Docker Image to Docker Repo # Step to build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: bimbstech24/swiss-docker # Name of the Docker image
        registry: docker.io # Docker registry to push the image to
        username: ${{ secrets.DOCKER_USER }} # Docker registry username from secrets
        password: ${{ secrets.DOCKER_PASSWORD }} # Docker registry password from secrets
        dockerfile: Dockerfile # Path to the Dockerfile
